### ISSUE TITLE
Add pytest in requirements.txt

### ISSUE THREAD

**Issue by Badr-MOUFAD** [mathurinm/github-assignment#7]
Add ``pytest`` in requirements.txt

Those who work with a virtual environment and install python packages with 
``
pip install -r requirements.txt 
``
may have troubles running the python scripts.

**Comment by Badr-MOUFAD** [comment]
@mathurinm, also add the ``flake8``, ``pydocstyle``

**Comment by mathurinm** [comment]
Hi Badr,
That's debatable : there are not required for the code to function, but only by the CI. So for teaching purposes it's ok to add them (though, it's important to be able to know how to install packagesà, but in a real repo, you wouldn't (have as few requirements as possible for your userbase).
I'll edit the readme instead
